// Study settings. Edit this file, then commit and push to update the live site.
window.STUDY_CONFIG = {
  // Change this when you start a new round, so returning raters start fresh.
  studyId: "video-study-v2",

  title: "Sign Language Generation Study",

  // Paste the Google Apps Script web app URL here (see README, step 2).
  // Leave empty to run in demo mode: answers stay in the browser and can be downloaded as CSV.
  scriptUrl: "https://script.google.com/macros/s/AKfycbxfnudJBletwS1fOEKIQSd3ZvBpax_OD7ZwwrTZTiQx4bBugneCz-MVSNnnp6ylVYWr/exec",

  // Shown on the welcome screen. Plain text; blank lines start a new paragraph.
  instructions: `Each video shows one English sentence in sign language, in several panels side by side. On the left is a real person signing (GT Video), with the sentence shown below it. Some videos also include a GT Mesh panel: a 3D avatar copying the real person's motion, shown for reference. The last three panels, labeled A, B and C (or Method A, B and C), are 3D avatars generated by different methods for the same sentence.

Watch the whole video, then choose which of A, B and C is most semantically aligned with the leftmost video (GT Video) — that is, whose signing conveys the same meaning most faithfully. There are no right or wrong answers — we are interested in your own judgement. You can replay a video before answering.

Please use a computer with a large screen rather than a phone. The study takes about 10 minutes. Your progress is saved, so you can close the page and come back later with the same participant ID.`,

  // Consent statement the rater must tick before starting. Set to "" to skip.
  consent: "I agree to take part in this study and understand my answers will be recorded anonymously.",

  // Ask for a participant ID. It is pre-filled from ?id=... or ?PROLIFIC_PID=... in the link.
  // If false, a random anonymous ID is generated.
  askRaterId: true,

  // The labels of the versions inside each video, in the order the buttons should appear.
  choices: ["A", "B", "C"],

  // Asked after each video; the answer is one of the choices. Add more to ask several things.
  questions: [
    { id: "semantic", text: "Which one — A, B or C — is most semantically aligned with the leftmost video?" },
  ],

  randomizeOrder: true,     // each rater gets their own order of videos (stable across reloads)
  requireFullWatch: true,   // answering unlocks only after the video has played to the end
  maxPlays: 3,              // how many times a rater may play each video (1 = no replay)

  // Shown on the final screen (e.g. a Prolific / MTurk completion code). Leave "" to hide.
  completionCode: "",
};
