// Study settings. Edit this file, then commit and push to update the live site.
window.STUDY_CONFIG = {
  // Change this when you start a new round, so returning raters start fresh.
  studyId: "video-study-v2",

  title: "Sign Language Generation Study",

  // Paste the Google Apps Script web app URL here (see README, step 2).
  // Leave empty to run in demo mode: answers stay in the browser and can be downloaded as CSV.
  scriptUrl: "https://script.google.com/macros/s/AKfycbxfnudJBletwS1fOEKIQSd3ZvBpax_OD7ZwwrTZTiQx4bBugneCz-MVSNnnp6ylVYWr/exec",

  // Shown on the welcome screen. Plain text; blank lines start a new paragraph.
  instructions: `Each video shows one English sentence in sign language, in several panels side by side. On the left is a real person signing (GT Video), with the sentence shown below it. Some videos also include a GT Mesh panel: a 3D avatar copying the real person's motion, shown for reference. The last three panels, labeled A, B and C (or Method A, B and C), are 3D avatars generated by different methods for the same sentence.

Watch the whole video, then choose which of A, B and C is most semantically aligned with the leftmost video (GT Video) — that is, whose signing conveys the same meaning most faithfully. For videos that include a GT Mesh, you will also rate how well the GT Mesh reflects the real video. There are no right or wrong answers — we are interested in your own judgement. You can replay a video before answering.

Please use a computer with a large screen rather than a phone. The study takes about 10 minutes. Your progress is saved, so you can close the page and come back later with the same participant ID.`,

  // Consent statement the rater must tick before starting. Set to "" to skip.
  consent: "I agree to take part in this study and understand my answers will be recorded anonymously.",

  // Ask for a participant ID. It is pre-filled from ?id=... or ?PROLIFIC_PID=... in the link.
  // If false, a random anonymous ID is generated.
  askRaterId: true,

  // Background questions asked once, after consent and before the first video.
  // Answers go to the Participants tab of the Sheet (one row per rater).
  // Each option is { value, label }: raters see the label, the Sheet stores the value.
  // Leave the list empty to skip this page.
  survey: [
    {
      id: "asl_level",
      text: "How would you rate your ASL proficiency?",
      options: [
        { value: "1 None", label: "1 – No knowledge of ASL" },
        { value: "2 Beginner", label: "2 – Beginner: I know some signs or basic phrases" },
        { value: "3 Intermediate", label: "3 – Intermediate: I can hold simple conversations" },
        { value: "4 Advanced", label: "4 – Advanced: I can follow most conversations comfortably" },
        { value: "5 Native/fluent", label: "5 – Native or fluent: ASL is my first language, or I use it fluently every day" },
      ],
    },
  ],

  // The labels of the versions inside each video, in the order the buttons should appear.
  choices: ["A", "B", "C"],

  // Asked after each video. By default the answer is one of the choices above (A, B, C).
  // A question with its own `options` is a rating scale instead: values 1..n, shown as buttons.
  // `showFor(video)` limits a question to some videos; video.panels is the number of panels
  // side by side (5 = GT Video, GT Mesh, A, B, C), filled in by make_video_list.py.
  questions: [
    { id: "semantic", text: "Which one — A, B or C — is most semantically aligned with the leftmost video?" },
    {
      id: "mesh_fidelity",
      text: "How well does the GT Mesh reflect the signing in the real video (GT Video)?",
      showFor: (video) => video.panels === 5,
      options: [
        { value: "1", label: "Very poorly" },
        { value: "2", label: "Poorly" },
        { value: "3", label: "Moderately" },
        { value: "4", label: "Well" },
        { value: "5", label: "Very well" },
      ],
    },
  ],

  randomizeOrder: true,     // each rater gets their own order of videos (stable across reloads)
  requireFullWatch: true,   // answering unlocks only after the video has played to the end
  maxPlays: 0,              // how many times a rater may play each video (0 = unlimited, 1 = no replay)

  // Shown on the final screen (e.g. a Prolific / MTurk completion code). Leave "" to hide.
  completionCode: "",
};
