#!/usr/bin/env python3
"""Scan videos/ and write videos.js, the list of videos the study shows.

Each video is one round: it already contains the versions to compare (A, B, C...)
side by side. Subfolders are fine. Run this again whenever you add, remove or
rename videos:

    python3 make_video_list.py

Each video's id is its path inside videos/ (e.g. "set1/clip01.mp4"); that id is what
appears in the video_id column of your Google Sheet.

It also writes mapping_template.csv: one row per video with empty A/B/C columns.
Fill in which method is in each position and paste it into the Mapping tab of the
Sheet (see README). The template is git-ignored so the mapping never becomes public.
"""

import csv
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
VIDEO_DIR = ROOT / "videos"
OUT = ROOT / "videos.js"
TEMPLATE = ROOT / "mapping_template.csv"
CONFIG = ROOT / "config.js"

EXTENSIONS = {".mp4", ".m4v", ".webm", ".mov", ".ogv"}
# Codecs that play in current Chrome, Firefox, Safari and Edge.
WEB_CODECS = {"h264", "vp8", "vp9", "av1"}
GITHUB_FILE_LIMIT = 100 * 1024 * 1024    # GitHub rejects files larger than this
GITHUB_FILE_WARN = 50 * 1024 * 1024
PAGES_SITE_LIMIT = 1024 * 1024 * 1024    # GitHub Pages sites should stay under 1 GB
# Same rule as the Apps Script: no control characters, and it can't start with = + - @.
ID_RE = re.compile(r"^[A-Za-z0-9_][^\x00-\x1f\x7f]{0,199}$")


def probe(path):
    """Return (codec, width, height) using ffprobe, or Nones if unavailable."""
    if not shutil.which("ffprobe"):
        return None, None, None
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "v:0",
             "-show_entries", "stream=codec_name,width,height", "-of", "json", str(path)],
            capture_output=True, text=True, timeout=30,
        )
        s = (json.loads(out.stdout or "{}").get("streams") or [{}])[0]
        return s.get("codec_name"), s.get("width"), s.get("height")
    except (OSError, subprocess.SubprocessError, ValueError):
        return None, None, None


def choice_labels():
    """Read the choices: [...] list from config.js (defaults to A, B, C)."""
    try:
        m = re.search(r"choices\s*:\s*\[([^\]]*)\]", CONFIG.read_text(encoding="utf-8"))
        labels = re.findall(r"[\"']([^\"']+)[\"']", m.group(1)) if m else []
        return labels or ["A", "B", "C"]
    except OSError:
        return ["A", "B", "C"]


def main():
    if not VIDEO_DIR.is_dir():
        VIDEO_DIR.mkdir()
        print(f"Created {VIDEO_DIR.relative_to(ROOT)}/ — put your video files there and run this again.")

    files = sorted(
        p for p in VIDEO_DIR.rglob("*")
        if p.is_file() and p.suffix.lower() in EXTENSIONS and not p.name.startswith(".")
    )

    entries, problems, total = [], 0, 0
    for path in files:
        rel = path.relative_to(VIDEO_DIR).as_posix()
        size = path.stat().st_size
        total += size
        mb = size / 1024 / 1024

        if not ID_RE.match(rel):
            print(f"  SKIP  {rel}: rename it so it starts with a letter, digit or _")
            problems += 1
            continue
        if size > GITHUB_FILE_LIMIT:
            print(f"  ERROR {rel}: {mb:.0f} MB — GitHub rejects files over 100 MB")
            problems += 1
        elif size > GITHUB_FILE_WARN:
            print(f"  warn  {rel}: {mb:.0f} MB — large files load slowly for raters")

        codec, width, height = probe(path)
        if codec == "hevc":
            print(f"  warn  {rel}: H.265/HEVC plays in Safari but not in most Chrome/Firefox setups")
        elif codec and codec not in WEB_CODECS:
            print(f"  ERROR {rel}: codec '{codec}' won't play in browsers (use H.264, VP9 or AV1)")
            problems += 1
        if width and width > 3840:
            print(f"  warn  {rel}: {width}x{height} is wider than most screens; it will be scaled down")

        entries.append({"id": rel, "src": "videos/" + quote(rel)})

    body = ",\n".join("  " + json.dumps(e, ensure_ascii=False) for e in entries)
    OUT.write_text(
        "// Generated by make_video_list.py. Re-run it after adding or removing videos.\n"
        "window.STUDY_VIDEOS = [\n" + (body + ",\n" if body else "") + "];\n",
        encoding="utf-8",
    )

    labels = choice_labels()
    with TEMPLATE.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["video_id"] + labels)
        for e in entries:
            w.writerow([e["id"]] + [""] * len(labels))

    print(f"\nWrote {OUT.name} with {len(entries)} video(s), {total / 1024 / 1024:.1f} MB total.")
    print(f"Wrote {TEMPLATE.name} (fill in which method is {', '.join(labels)} in each video).")
    if total > PAGES_SITE_LIMIT:
        print("  warn  over 1 GB in total; GitHub Pages may refuse to publish the site.")
    if not shutil.which("ffprobe"):
        print("  (install ffmpeg to also check that each file's codec plays in browsers)")
    if problems:
        print(f"{problems} problem(s) above need fixing before you publish.")
        sys.exit(1)


if __name__ == "__main__":
    main()
