#!/usr/bin/env python3
"""Scan videos/ and write videos.js, the list of clips the study shows.

Run it again whenever you add, remove or rename videos:

    python3 make_video_list.py

Each video's id is its path inside videos/ (e.g. "methodA/clip01.mp4"); that id is
what appears in the video_id column of your Google Sheet. Subfolders are fine.
"""

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
VIDEO_DIR = ROOT / "videos"
OUT = ROOT / "videos.js"

EXTENSIONS = {".mp4", ".m4v", ".webm", ".mov", ".ogv"}
# Codecs that play in current Chrome, Firefox, Safari and Edge.
WEB_CODECS = {"h264", "vp8", "vp9", "av1"}
GITHUB_FILE_LIMIT = 100 * 1024 * 1024    # GitHub rejects files larger than this
GITHUB_FILE_WARN = 50 * 1024 * 1024
PAGES_SITE_LIMIT = 1024 * 1024 * 1024    # GitHub Pages sites should stay under 1 GB
# Same rule as the Apps Script: no control characters, and it can't start with = + - @.
ID_RE = re.compile(r"^[A-Za-z0-9_][^\x00-\x1f\x7f]{0,199}$")


def video_codec(path):
    if not shutil.which("ffprobe"):
        return None
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "v:0",
             "-show_entries", "stream=codec_name", "-of", "csv=p=0", str(path)],
            capture_output=True, text=True, timeout=30,
        )
        return out.stdout.strip() or None
    except (OSError, subprocess.SubprocessError):
        return None


def main():
    if not VIDEO_DIR.is_dir():
        VIDEO_DIR.mkdir()
        print(f"Created {VIDEO_DIR.relative_to(ROOT)}/ — put your video files there and run this again.")

    files = sorted(
        p for p in VIDEO_DIR.rglob("*")
        if p.is_file() and p.suffix.lower() in EXTENSIONS and not p.name.startswith(".")
    )

    entries, problems, total = [], 0, 0
    for path in files:
        rel = path.relative_to(VIDEO_DIR).as_posix()
        size = path.stat().st_size
        total += size
        mb = size / 1024 / 1024

        if not ID_RE.match(rel):
            print(f"  SKIP  {rel}: rename it so it starts with a letter, digit or _")
            problems += 1
            continue
        if size > GITHUB_FILE_LIMIT:
            print(f"  ERROR {rel}: {mb:.0f} MB — GitHub rejects files over 100 MB")
            problems += 1
        elif size > GITHUB_FILE_WARN:
            print(f"  warn  {rel}: {mb:.0f} MB — large files load slowly for raters")

        codec = video_codec(path)
        if codec == "hevc":
            print(f"  warn  {rel}: H.265/HEVC plays in Safari but not in most Chrome/Firefox setups")
        elif codec and codec not in WEB_CODECS:
            print(f"  ERROR {rel}: codec '{codec}' won't play in browsers (use H.264, VP9 or AV1)")
            problems += 1

        entries.append({"id": rel, "src": "videos/" + quote(rel)})

    body = ",\n".join("  " + json.dumps(e, ensure_ascii=False) for e in entries)
    OUT.write_text(
        "// Generated by make_video_list.py. Re-run it after adding or removing videos.\n"
        "window.STUDY_VIDEOS = [\n" + (body + ",\n" if body else "") + "];\n",
        encoding="utf-8",
    )

    print(f"\nWrote {OUT.name} with {len(entries)} video(s), {total / 1024 / 1024:.1f} MB total.")
    if total > PAGES_SITE_LIMIT:
        print("  warn  over 1 GB in total; GitHub Pages may refuse to publish the site.")
    if not shutil.which("ffprobe"):
        print("  (install ffmpeg to also check that each file's codec plays in browsers)")
    if problems:
        print(f"{problems} problem(s) above need fixing before you publish.")
        sys.exit(1)


if __name__ == "__main__":
    main()
